vectorsearch_config:
  pipeline_type: CONTINUOUS
embedding_config:
  embedding_endpoint_name: databricks-bge-large-en
  embedding_tokenizer:
    tokenizer_model_name: BAAI/bge-large-en-v1.5
    tokenizer_source: hugging_face
pipeline_config:
  file_format: pdf
  parser:
    name: pypdf
    config: {}
  chunker:
    name: langchain_recursive_char
    config:
      chunk_size_tokens: 1024
      chunk_overlap_tokens: 512
